language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - make test
  - coverage run --source=collection_json make test
after_success: coveralls
